### ISSUE TITLE
Add option to silence tqdm bar

### ISSUE THREAD

**Issue by andreped** [JoHof/lungmask#1]
As I'm deploying your model quite often in a subprocess, with a high-level tqdm for number of samples/CTs to process, it would be convenient if it was possible to silence the tqdm bar from running inference. Ideally as a flag.

**Comment by JoHof** [comment]
Hi Andre,

wouldn't it be a solution to capture the output of your subprocesses? I am unsure how many people need such a "silent mode".

**Comment by andreped** [comment]
Oh, my bad. I had a silly bug in my code which resulted in tqdm being printed even though I disabled "all" prints. To completely mute the any relevant prints using lungmask in a subprocess:
`
import subprocess as sp
sp.check_call(["lungmask", path_to_some_ct, path_to_save_pred], stderr=sp.DEVNULL, stdout=sp.DEVNULL
`
