### ISSUE TITLE
A runtime error

### ISSUE THREAD

**Issue by WuYan98** [JoHof/lungmask#10]
Hi, when I give the path to OUTPUT file,  an error occurs: 
sitk::ERROR: Unable to determine ImageIO writer for "/content/OUTPUT"
can you suggest something about it?

**Comment by JoHof** [comment]
You have to specify a file type. e.g. /content/OUTPUT.nii.gz

**Comment by WuYan98** [comment]
> You have to specify a file type. e.g. /content/OUTPUT.nii.gz

Thank you very much!
