### ISSUE TITLE
Which version of SimpleITK should be used？

### ISSUE THREAD

**Issue by yixuanli1230** [JoHof/lungmask#102]
When I use SimpleITK 2.x (e.g. 2.3.1 or 2.0.1), running _**“lungmask input output”**_ gives me the following error.
![1](https://github.com/JoHof/lungmask/assets/124167503/ac226c71-2dd7-41a7-91a8-cc36770a9694)

When I use SimpleITK 1.x (e.g. 1.2.3 or 1.2.4), I get the following error：
![2](https://github.com/JoHof/lungmask/assets/124167503/1030bdb6-92fb-486d-a21d-693d5ac95ef3)

So, I would like to know which version of SimpleITK should be installed for successful testing.

**Comment by JoHof** [comment]
Hi, 
use a current version of SimpleITK (2.x) but specify the output file format through a file ending. E.g. `.../lungmask-master/tests/output.nii.gz` to save in NIFI format.

**Comment by yixuanli1230** [comment]
Got it. Thanks!
