### ISSUE TITLE
URLError when using LTRCLobes_R231 and LTRCLobes models on GPU

### ISSUE THREAD

**Issue by karolinasenkow** [JoHof/lungmask#107]
I am encountering an issue with the lungmask package. When trying to use the `LTRCLobes_R231` and `LTRCLobes` models on a GPU, I receive the following error:
`URLError: <urlopen error unknown url type: https>`

However, the `R231` model runs successfully on the GPU, and the `LTRCLobes_R231` and `LTRCLobes` models work on the CPU without any issues. It seems that the error occurs during the model download process over HTTPS.

Could you, please, look into this issue and provide a fix?

**Comment by JoHof** [comment]
Hi Karolina,

I would happy to help that is not enough information. What you describe sounds almost impossible. The weights are downloaded only once. I can't think of any reason why the model should be re-downloaded when using the GPU. It sounds like you are running CPU vs. GPU on different machines with eventually different environments. In case you want to use the package in an environment where you don't have access to the internet you can download the weights manually. You can find the ulrs here [https://github.com/JoHof/lungmask/blob/0653c7019200eb27253c540f731583466fc3c304/lungmask/mask.py#L22-L35](https://github.com/JoHof/lungmask/blob/0653c7019200eb27253c540f731583466fc3c304/lungmask/mask.py#L22-L35), and then provide the path to the weights file with `--modelpath`.

The downloading and caching of the weights is fully handled by torch in case you want to further investigate this: [https://pytorch.org/docs/stable/hub.html#torch.hub.load_state_dict_from_url](https://pytorch.org/docs/stable/hub.html#torch.hub.load_state_dict_from_url)
