### ISSUE TITLE
Convert to tensorflow model

### ISSUE THREAD

**Issue by Jorisfournel** [JoHof/lungmask#13]
Hello again,

I had the idea to use your models as pre-trained models for segmenting 
lungs and lesions in COVID, I tried to convert it to a tensorflow model with onnx
but I didn't succeed. Do you think the model and weights could be converted
and made accessible for tensorflow as well as .h5 files for example? 
Apologies for asking such things ^^,

Thanks anyway,
Joris

**Comment by JoHof** [comment]
Hi,

I think in principle its possible. Why does onnx not work? You can also rebuild the model in tensorflow and use the weights from the from my model. However, I have no plans to do this myself in the future.

**Comment by Jorisfournel** [comment]
Yes that's what I wanted to do and I tried all the afternoon but ended with
various errors, I don't have much experience yet in doing that..
The idea was then to change the number of output maps to add the ground
glass and condensations.

**Comment by JoHof** [comment]
I have done that and it works well with the 100 slices form medseg dataset. I will release a lung pattern unet shortly
