### ISSUE TITLE
utils.py contains "import fill_voids" but the fill_voids.py is not available

### ISSUE THREAD

**Issue by nadimpallipranav** [JoHof/lungmask#14]
Dear Johannes,

When I tried to segment a test image, I was unable to proceed due to the absence of the fill_voids.py or even a function that does the same. I kindly request, if possible, that we include the file in the next commit. 

`ImportError                               Traceback (most recent call last)
<ipython-input-2-b3409c419eb2> in <module>()
     13 
     14 
---> 15 from lungmask import mask
     16 import SimpleITK as sitk

~/lungmask-git/lungmask/mask.py in <module>()
      1 import numpy as np
      2 import torch
----> 3 from . import utils
      4 import SimpleITK as sitk
      5 from .resunet import UNet

~/lungmask-git/lungmask/utils.py in <module>()
      9 import logging
     10 from tqdm import tqdm
---> 11 import fill_voids
     12 
     13 

ImportError: No module named 'fill_voids'`

Best regards

**Comment by JoHof** [comment]
fill_voids is a dependecy
