### ISSUE TITLE
Mask values in medicalsegmentation.com dataset

### ISSUE THREAD

**Issue by ncovgt2020** [JoHof/lungmask#16]
Hi,

Thanks for sharing your work. I got the lung masks you kindly produced and are shared [here](http://medicalsegmentation.com/covid19/). I see the masks have values ranging from 1 to 3. Could you please explain what each value correspond to? Something like `1 = right lung, 2= left lung` etc. Thanks

**Comment by JoHof** [comment]
Hi,

yes 1 is right lung and 2 is left lung. the voxels with value 3 are artefacts and I wasn't aware of them. Thanks for letting me know. I will send a corrected version to medseg. However, they are single voxels at the lung border, you can simply ignore them.

**Comment by JoHof** [comment]
Hi,

I sent the corrected segmentations to medseg. They will be updated shortly
