### ISSUE TITLE
LTRCLobes_R231 model error

### ISSUE THREAD

**Issue by nicolocardobi** [JoHof/lungmask#20]
To whom it may concern,

I've a problem with the LTRCLobes_R231 model. If I run it, I obtain the following error:

lungmask /Chest_CT/S700830/S30 /Chest_CT/out/output.nii.gz --modelname LTRCLobes_R231
INFO:root:Load model
INFO:root:Looking for dicoms in /Chest_CT/S700830/S30
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 830/830 [00:01<00:00, 700.76it/s]
INFO:root:There are 1 volumes in the study
INFO:root:Infer lungmask
Traceback (most recent call last):
  File "/home/nico/.local/bin/lungmask", line 11, in <module>
    load_entry_point('lungmask==0.2.3', 'console_scripts', 'lungmask')()
  File "/home/nico/.local/lib/python3.8/site-packages/lungmask/__main__.py", line 39, in main
    result = mask.apply_fused('LTRCLobes','R231')
  File "/home/nico/.local/lib/python3.8/site-packages/lungmask/mask.py", line 93, in apply_fused
    res_l = apply(image, mdl_l, force_cpu=force_cpu, batch_size=batch_size,  volume_postprocessing=volume_postprocessing)
  File "/home/nico/.local/lib/python3.8/site-packages/lungmask/mask.py", line 26, in apply
    voxvol = np.prod(image.GetSpacing())
AttributeError: 'str' object has no attribute 'GetSpacing'

If I use the default model, i have no errors.

What can I do ot resolve this issue?

Best Regards

P.s.: I changed the dataset, same error.

**Comment by JoHof** [comment]
Hi nicolo,

oh no, what a stupid bug. I am sorry. It should be fixed now. can you confirm that it works for you now?

**Comment by nicolocardobi** [comment]
Hi JoHof,

re-downloaded the model and re-tested. Unfortunaltely, same error.

Best Regards

**Comment by JoHof** [comment]
Hi,

you need to re-install the package!
```
pip uninstall lungmask
pip install git+https://github.com/JoHof/lungmask
```
this should do the trick

**Comment by nicolocardobi** [comment]
Ok, it's working. Thanks!

Is it normal that after hitting 100% of the second progress bar (few seconds) and before the terminal output:

INFO:root:Save result to: /home/nico/Desktop/Chest_CT/out/output_lobes.nii.gz

elapse several minutes? CPU and GPU are apparently idling in that time interval.

The default model, despite it is simpler,  takes seconds to complete.

**Comment by JoHof** [comment]
Hi! Thanks for your feedback!

Yes, that's normal. The fusing process can vary between a few seconds and several minutes. However this strongly depends on the number of slices and how different the R231 and LTRCLobes predictions were. I added a progressbar to the fusing process. So if you update the package one more time there will be a third progress bar that will help you to better estimate the runtime.
