### ISSUE TITLE
 --modeltype resunet not working

### ISSUE THREAD

**Issue by GiulioBen** [JoHof/lungmask#21]
From the help page i see the resunet model, but it's not working at all.

The error is
`    
model_url, n_classes = model_urls[(modeltype, modelname)]
KeyError: ('resunet', 'LTRCLobes')
`

clearly because the array doesn't contain urls for resunet model.

Has not it been implemented yet?

Regards

GB

**Comment by JoHof** [comment]
Hi Giulio,

thank's for brining this up. The resunet did not give any improvements over the regular u-net. That's why I didn't upload it. I will remove this from the help text.
