### ISSUE TITLE
Lung segmentation - extra segment outsize the body mass

### ISSUE THREAD

**Issue by stergioc** [JoHof/lungmask#22]
Dear @JoHof,

thanks for sharing this work. I am posting this issue just because it seems like a simple fix that can increase the robustness of the whole pipeline. While checking the performance on some scans I figured than in some cases, the model produced an additional segment outside of the body mass along with the left/right labels. I found cases with both 1 and 2 as label for this extra segment. Here is an example:

![issue](https://user-images.githubusercontent.com/4221880/80747332-92216600-8b23-11ea-9e65-81ac0f761066.png)

I would guess that a simple counting of the connected components in the final segmentation could fix this issue.

**Comment by JoHof** [comment]
Hi,

thanks for reporting this. That's weird, post-processing should take care of this. Are you eventually using an older version? Otherwise this is a bug. Could you eventually share such a case?

**Comment by stergioc** [comment]
Hello, I am indeed using the latest version `lungmask==0.2.3`. Looking a bit closer to the intermediate results it seems that the problem can be identified after this line:

https://github.com/JoHof/lungmask/blob/1018e41f78777260bb8685e868fb61cea3d99e2c/lungmask/utils.py#L200

in the case that the left/right lung are touching then they both belong to the same label mask and therefore the second largest region is outside of the lung region.

I hope this helps.

**Comment by JoHof** [comment]
Absolutely! Thank you so much! Will fix that shortly...

**Comment by JoHof** [comment]
Should be fixed. Let me know if there are any other issues...

**Comment by stergioc** [comment]
Indeed it is fixed for the examples I checked. Cool :ok_hand:
