### ISSUE TITLE
mask.apply(image) not working

### ISSUE THREAD

**Issue by Ralphchahwan** [JoHof/lungmask#24]
Dear @JoHof 
Thank you so much for this amazing library, but for some reason it is not working out for me
I hope you could be of help

When I read the image using SimpleITK and then try to apply a mask on that image, I get an error:
`IndexError: index 4 is out of bounds for axis 0 with size 4`

The error happens in the mask function on line 29:
`inimg_raw = np.flip(inimg_raw, np.where(directions[[0,4,8]][::-1]<0)[0]`

I am trying to work on CT-images downloaded online, their format is either jpg or png

What can I do to fix this issue?

**Comment by JoHof** [comment]
Hi Ralph,

the models were not trained with such images in mind. However, I just added support for jpg and png images using some heuristics to estimate the HU. Download the current version (0.2.5) and use the --noHU tag. Be aware that the results on these kind of images may not be optimal.
