### ISSUE TITLE
What is the max label for LTRCLobes_R231 segmentation?

### ISSUE THREAD

**Issue by bartmch** [JoHof/lungmask#25]
Great work! Using LTRCLobes_R231 I got 6 labels. Am I assuming correctly that the 6th label is where the LTRCLobes and R231 segmentations don't agree during the fusion step? If that assumption is correct LTRCLobes_R231 will output max 6 labels (right lung = [3,4,5], left lung = [1,2])

**Comment by JoHof** [comment]
Hi, there shouldn't be a a 6th label. It's probably a bug in the fusion part. Are you using the most current version?

**Comment by JoHof** [comment]
Does the problem still exist? Otherwise I will close this issue...

**Comment by bartmch** [comment]
yes I’m using the latest version. We are talking about a few pixels at the
pulmonary artery so I’m guessing it’s the “mismatch”. You can close it for
now as I’m not sure when I’ll have time again to investigate this further.

**Comment by JoHof** [comment]
Thanks for you reply! I think I now know whats going on. Any "mismatch" should be mapped to a lobe label. So there shouldn't be of these left in the end. However, it seems that if there are no neighbors, the mismatch is not removed. I will check if this is the case and update eventually. Thanks again for reporting this issue

**Comment by JoHof** [comment]
This should be fixed now

**Comment by mdafokus** [comment]
Hi @JoHof. First of all, thank you for your work!
I try to investigate the `LTRCLobes_R231` model and become six labels [0,...,5] as output. I use the current version of your code. 

Do you have any idea what can I do to resolve this issue to get only 5 labels?

**Comment by JoHof** [comment]
Background and the 5 lobes, isn't that what you would expect?
