### ISSUE TITLE
how to get the LTRCLobes_R231 model

### ISSUE THREAD

**Issue by ziqiangxu** [JoHof/lungmask#27]
It seems that the model hasn't been upload

**Comment by ziqiangxu** [comment]
> It seems that the model hasn't been upload

or invoke the function apply_fused insted?

**Comment by JoHof** [comment]
Its in the readme. Use the apply_fused function

**Comment by ziqiangxu** [comment]
> Its in the readme. Use the apply_fused function

Thanks
