### ISSUE TITLE
Recursive lungmask?

### ISSUE THREAD

**Issue by MadisLemsalu** [JoHof/lungmask#28]
Is it possible to recursively produce a lungmask for each dicom in a folder and maintain the same file name? 

For example with a -f flag? 

`lungmask -f ./dicom ./output
`

**Comment by JoHof** [comment]
Hi,

there is no such functionality implemented in the lungmask python package. However, it shouldn't be too hard to write a python script to do that. Do you really want to process each single dicom file and get one result file for each or do you want to process the full series? For the first, a simple bash script will do (https://stackoverflow.com/questions/8055501/how-to-copy-in-bash-all-directory-and-files-recursive) for the second you can write a python script utilizing the utils.read_dicom function in the lungmask package which recursively looks for series in a given folder and loads them.
