### ISSUE TITLE
My own nii file failed, it seems that the error is caused by the zooming in and out of the image?

### ISSUE THREAD

**Issue by shuanggou** [JoHof/lungmask#29]
I have a nii file, shape is (41, 226, 295), when using the lungmask demo, it failed. (I have tried many other files and succeed. )
![image](https://user-images.githubusercontent.com/11666931/83160588-fa229680-a139-11ea-8e29-74aba9ffe291.png)

**Comment by JoHof** [comment]
Hi,

thanks for reporting this bug. It should be now (version 0.2.7).

**Comment by shuanggou** [comment]
> Hi,
> 
> thanks for reporting this bug. It should be fixed now (version 0.2.7).

Thanks for fixing the bug, but I met the similar error again, this time the input shape is (39, 242, 358).
![image](https://user-images.githubusercontent.com/11666931/83211735-7e076d80-a190-11ea-8e2b-0156924b67ba.png)

**Comment by JoHof** [comment]
Oh shoot. There was a line in code assuming quadratic input. Now it should really be fixed
