### ISSUE TITLE
TIF Files

### ISSUE THREAD

**Issue by saranggoel** [JoHof/lungmask#39]
Hello,

I was trying to run some tif files, but it keeps giving me the error that I have to many indices for the array. This is probably due to my images being a 512x512 resolution, while the code accepts 256x256. Do you know what I may change in order for these tif files to work?

**Comment by saranggoel** [comment]
Additionally, when I convert my tifs down to 256x256, it still gives me the IndexError.

**Comment by JoHof** [comment]
what error do you get? 

Let me know that this gives you...
```
import SimpleITK as sitk
i = sitk.ReadImage([PATH_TO_YOUR_FILE])
i_np = sitk.GetArrayFromImage(i)
print(i_np.shape)
print(i_np.min())
print(i_np.max())
```

**Comment by saranggoel** [comment]
np.shape: (1, 512, 512)
np.min: 0.0
np.max: 2819.0

Thank you so much for helping me!

**Comment by saranggoel** [comment]
If you need to know the error, it says IndexError: too many indices for array

**Comment by JoHof** [comment]
I assume it's an issue resulting from the wrong intensity encoding. A CT scan is supposed to be encoded in hounsfield units (air is -1000, water 0 and bone >1000) Try to subtract -1000 from the image before applying the model:

```
from lungmask import mask
import SimpleITK as sitk

i = sitk.ReadImage([PATH_TO_YOUR_FILE])
i_np = sitk.GetArrayFromImage(i)
i_np = i_np-1000
i_hu = sitk.GetImageFromArray(i_np)
segmentation = mask.apply(i_hu)
```
You also have to make sure that the orientation is right. How is it look when you make:
```
plt.imshow(i_np[0])
```

**Comment by saranggoel** [comment]
It still gives the error: IndexError: too many indices for array, even after I fix the HU value range.

**Comment by saranggoel** [comment]
(512, 512)
-1000.0
1000.0

This is the shape, min, and max vals.

**Comment by JoHof** [comment]
Can you post the stack trace of the error?

**Comment by saranggoel** [comment]
IndexError: too many indices for array
Traceback:

File "c:\users\rakes\anaconda3\envs\tensorflow\lib\site-packages\streamlit\script_runner.py", line 332, in _run_script
    exec(code, module.__dict__)
File "D:\COVID-CT-master\baseline methods\DenseNet169\website.py", line 480, in <module>
    main()
File "D:\COVID-CT-master\baseline methods\DenseNet169\website.py", line 123, in main
    regions()
File "D:\COVID-CT-master\baseline methods\DenseNet169\website.py", line 385, in regions
    segmentation = mask.apply(i_hu, volume_postprocessing= False)  # default model is U-net(R231)
File "c:\users\rakes\anaconda3\envs\tensorflow\lib\site-packages\lungmask\mask.py", line 46, in apply
    tvolslices, xnew_box = utils.preprocess(inimg_raw, resolution=[256, 256])
File "c:\users\rakes\anaconda3\envs\tensorflow\lib\site-packages\lungmask\utils.py", line 26, in preprocess
    (im, m, box) = crop_and_resize(imgmtx[i, :, :], width=resolution[0], height=resolution[1])

**Comment by JoHof** [comment]
The image should have a dimension for the slices just like you posted (np.shape: (1, 512, 512)) but not like this  (512, 512)

**Comment by saranggoel** [comment]
The dimension I originally posted (1, 512, 512), I accidentally used NII images. However, (512, 512) is TIF images. Does that mean that NII images will only work?

**Comment by JoHof** [comment]
You can simply add a dimension like so
`img=img[None,::]`

**Comment by saranggoel** [comment]
Thank you so much! I works now!

**Comment by saranggoel** [comment]
This issue really isn't related to what I have mentioned above, but I didn't want to open a new issue for it. I was just wondering if this was how the U-net(LTRC Lobes_R231) was supposed to look like:

![image](https://user-images.githubusercontent.com/64043281/103034757-3b8def80-452b-11eb-9feb-4ee39adefd92.png)

If not, do you know what may be the problem? Thanks!

**Comment by JoHof** [comment]
It's supposed to look like that

**Comment by saranggoel** [comment]
Thank you so much!
