### ISSUE TITLE
Lobe segmentation

### ISSUE THREAD

**Issue by riccardosamperna** [JoHof/lungmask#4]
Dear @JoHof,

first of all, thanks for sharing your code publicly and providing an easy way to run inference with your network.

I just wanted to report some strange behaviours running the LTRCLobes version of your network for some of the images in my dataset. Please look at the example below to have an idea:

![example](https://user-images.githubusercontent.com/6599726/78014082-b3860b00-7347-11ea-8628-17179e2daa1b.jpg)

Have you experienced similar behaviours using your network for lobe segmentation?

**Comment by JoHof** [comment]
Hi @riccardosamperna,

thanks for reporting this case! Unfortunately, results like these are expected for the LTRCLobes model on very pathological lungs. The model processes on a slice by slice basis and thus is quite limited in estimating lobes when fissures are not visible. Also, the LTRC training data contains no or little cases with soft tissue emphysema or collapsed lobes like your case. I recommend using the R231 model if you don't necessarily need the lobes. If you want to keep this rough lobe estimates but get rid of the false positive soft tissue emphysema you could run the R231 model to mask the result of the LTRCLobes. 

Once again, many thanks for reporting this case! I will let this issue open for others to see the limitations of the LTRCLobes model.

**Comment by riccardosamperna** [comment]
Thank you for your answer @JoHof
