### ISSUE TITLE
Apply mask on png image

### ISSUE THREAD

**Issue by IsabelleCur** [JoHof/lungmask#40]
Thank you so much for this work! But I have problems applying the mask on png images.
This is the original image:
![CT0014](https://user-images.githubusercontent.com/49813750/103607628-595c4b00-4f54-11eb-98d4-f67f7295ebe6.png)
This is the code:
`
import SimpleITK as sitk
from lungmask import mask #lung segmentation model
model = mask.get_model('unet','R231CovidWeb')
i = sitk.ReadImage("../trainData/subject-level/Cap/cap003/CT0014.png")

i_np = sitk.GetArrayFromImage(i)
print(i_np.shape)
print(i_np.min())
print(i_np.max())

i_np2=i_np[None,::]
i_hu=sitk.GetImageFromArray(i_np2)

segmentation = mask.apply(i, model, noHU=True)
print(segmentation.shape)
print(segmentation.min())
print(segmentation.max())

s2 = mask.apply(i_hu, model)
print(s2.shape)
print(s2.min())
print(s2.max())
`
The output:
(512, 512)
38
255
/home/mist/.local/lib/python3.6/site-packages/lungmask/mask.py:51: FutureWarning: The behavior of rgb2gray will change in scikit-image 0.19. Currently, rgb2gray allows 2D grayscale image to be passed as inputs and leaves them unmodified as outputs. Starting from version 0.19, 2D arrays will be treated as 1D images with 3 channels.
  tvolslices = skimage.color.rgb2gray(inimg_raw)

(1, 512, 512)
0
2

(1, 512, 512)
0
0

In the above code, I tried both: with the --noHU tag, and without the tag(adding a dimension by img=img[None,::]), But only got an almost all black mask using both ways. Could you please tell me why and how to modify it? Thanks so much!

**Comment by JoHof** [comment]
Hi Isabelle,

when the noHU tag doesn't work the only chance is to estimate the HU values yourself. looking at your image, 38 seems to correspond to air (-1000) and upper threshold is rather low, so I would estimate its at 0 (water):

![image](https://user-images.githubusercontent.com/11867033/103621375-63228600-4f35-11eb-9e72-64cf2ab00496.png)

**Comment by IsabelleCur** [comment]
> Hi Isabelle,
> 
> when the noHU tag doesn't work the only chance is to estimate the HU values yourself. looking at your image, 38 seems to correspond to air (-1000) and upper threshold is rather low, so I would estimate it's at 0 (water):
> 
> ![image](https://user-images.githubusercontent.com/11867033/103621375-63228600-4f35-11eb-9e72-64cf2ab00496.png)

Thanks for your prompt response! But it still didn't work well when the original image is kind of grey like this:
![CT0074](https://user-images.githubusercontent.com/49813750/103632217-f338ed80-4f7e-11eb-89b1-cc0ba846a040.png)
In this situation, the mask returns:
![截屏2021-01-05 下午5 54 00](https://user-images.githubusercontent.com/49813750/103632293-0e0b6200-4f7f-11eb-94df-a6ff29fb2161.png)

Is there any solutions? Thanks again!

**Comment by JoHof** [comment]
This tool is intended to be used with real CT images that are encoded in hounsfield units. If you have a large set of pngs with random intensities then this is not the right tool for you. If you are ok with specifying the HU range for each image yourself then it will work just fine. E.g. for this image you would need to replace '(i_tmp*1000)-1000' with '(i_tmp*2000)-1000'

**Comment by IsabelleCur** [comment]
OK, maybe I should consider other tools. Thanks!
