### ISSUE TITLE
Error when processing directory to directory

### ISSUE THREAD

**Issue by davidssmith** [JoHof/lungmask#43]
This is a great code, thanks for sharing!

I am trying to process a bunch of directories, but when I run the command 

`lungmask input/1864/19640829_CTCAP/NA_90_OMNI_350 output/1864_19640829_CTCAP_NA_90_OMNI_350`, 

I get this error:
```
INFO:root:Save result to: output/1864_19640829_CTCAP_NA_90_OMNI_350/
Traceback (most recent call last):
  File "/home/dss/.local/bin/lungmask", line 8, in <module>
    sys.exit(main())
  File "/home/dss/.local/lib/python3.8/site-packages/lungmask/__main__.py", line 60, in main
    sys.exit(sitk.WriteImage(result_out, args.output))
  File "/home/dss/.local/lib/python3.8/site-packages/SimpleITK/extra.py", line 394, in WriteImage
    return writer.Execute(image)
  File "/home/dss/.local/lib/python3.8/site-packages/SimpleITK/SimpleITK.py", line 5518, in Execute
    return _SimpleITK.ImageFileWriter_Execute(self, *args)
RuntimeError: Exception thrown in SimpleITK ImageFileWriter_Execute: /tmp/SimpleITK/Code/IO/src/sitkImageFileWriter.cxx:206:
sitk::ERROR: Unable to determine ImageIO writer for "output/1864_19640829_CTCAP_NA_90_OMNI_350/"
```

Any idea why this might be happening? I have verified that the code works perfectly on a single file, and the output dir exists and is writable.

**Comment by JoHof** [comment]
You have to specify a datatype for the output for example output/1864_19640829_CTCAP_NA_90_OMNI_350.nii.gz

**Comment by davidssmith** [comment]
Yes, input is DICOM. I cannot process a directory to a directory then?

Does the single file output need to be a format that can accept multiple images?

**Comment by ahmed1996said** [comment]
@davidssmith, same issue here. I get this error with some .dcm images but seems to work fine with others. Did you find a solution?

**Comment by JoHof** [comment]
One call to the tool is processing one image. If the input is a folder, then it will look for a DICOM series, process this volumetric image and stores the segmentation to whatever file is specified as the output. The output can not be folder, you have to specify a filename with and ending that determins the filetype.  `sitk::ERROR: Unable to determine ImageIO writer for` because sitk can not know what you want if you don't specify a filetype
