### ISSUE TITLE
ValueError: numpy.ndarray size changed, may indicate binary incompatibility

### ISSUE THREAD

**Issue by manjitullal** [JoHof/lungmask#44]
I ran the below command and getting the error.

!lungmask '/content/images_001/images/' '/content/images_001/mask/'

the dataset i am using is this https://www.kaggle.com/nih-chest-xrays/data

Error:

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

is there a problem with the type of input image

**Comment by JoHof** [comment]
This is a segmentation tool for CT scans and not X-Ray so it won't work anyway.

**Comment by manjitullal** [comment]
thanks for reply, i had assumed CT scan and X-Ray are basically images so the image segmentation technique of one image should work on the other image too but , looks like my understanding is not right
