### ISSUE TITLE
Question about direction pre-processing one liner

### ISSUE THREAD

**Issue by dscarmo** [JoHof/lungmask#45]
Hello, i am very intestered by this one-liner that i found in your pre-processing of simpleitk images:

    np.flip(data, np.where(directions[[0,4,8]][::-1]<0)[0])

Visualizing the data before and after this operation, it seems that it normalizes the direction of the CT volume.

Can you confirm this line alone is enough to normalize the 3D direction of data extracted using SimpleITK, from DCM and NIFT images?

Thank you!

**Comment by JoHof** [comment]
Hi Diedre,

yes, that is the purpose of the line. It normalizes the orientation with respect to the patient. For example, if the patient was scanned in prone position (that is, lying on the belly) the image will also be flipped. This way of normalization is a bit limited though as it assumes the coordinate system being orthogonal to the patient. This is true for almost all chest ct scans but I would not recommend to it that way for MR imaging.

**Comment by dscarmo** [comment]
Thanks for the clarification! I was surprised as to how lungmask was able to work in hundreds of CTs I and my team had access. Those being from multiple different sources, and with that direction normalization apparently working. 

Keep up the good work!
