### ISSUE TITLE
Segmentation on LIDC-IDRI Dataset

### ISSUE THREAD

**Issue by devaletanmay** [JoHof/lungmask#57]
Hi @JoHof 

I tried using the Unet R231 model on Dicom Images from the [LIDC-IDRI Dataset](https://wiki.cancerimagingarchive.net/display/Public/LIDC-IDRI#:~:text=The%20Lung%20Image%20Database%20Consortium,with%20marked%2Dup%20annotated%20lesions.&text=Seven%20academic%20centers%20and%20eight,set%20which%20contains%201018%20cases.) 
The model returned an empty mask. 
I have attached a zip file with 1 dicom file and the code I am using to find the mask.
[Segmentation_On_LIDC_IDRI_Dataset.zip](https://github.com/JoHof/lungmask/files/7083387/Segmentation_On_LIDC_IDRI_Dataset.zip)

Thanks!

**Comment by JoHof** [comment]
Hi @devaletanmay, 

this is a tool for lung segmentation in CT scans not X-ray

**Comment by devaletanmay** [comment]
They are CT scans
As mentioned on https://wiki.cancerimagingarchive.net/display/Public/LIDC-IDRI
(The Lung Image Database Consortium image collection (LIDC-IDRI) consists of diagnostic and lung cancer screening thoracic computed tomography (CT) scans with marked-up annotated lesions.)

**Comment by JixiangChen-Jimmy** [comment]
Hi, any updates for solving this issue? I am encountering the same problem.

**Comment by JoHof** [comment]
The Dicom file posted by devaletanmay is an X-ray and not a CT.
