### ISSUE TITLE
Fine Tune / retrain with more data ?

### ISSUE THREAD

**Issue by Jorisfournel** [JoHof/lungmask#6]
Hello,
First of all thank you very much for this! 
It's easy to use and working great.
I had a few question, I'm currently working on a model
to segment the COVID casis and plan to use your model
or a separate model to get the lung volumes or as a way 
to initialize segmentations of lungs to be manually refined
in order to train a model of my own.
What do you think is the best solution for me ?
I have no idea what amount of data you used to have a robust model
and therefore I don't know how much data I need to label to have a 
model working as good. Another solution would be to be able
to add the data I will produce and fine-tune/retrain your model as
more data get collected, would that be desirable/doable, in my case ?

Anyway be blessed for your contribution!
Joris

**Comment by JoHof** [comment]
Hi @Jorisfournel 

The motivation for this work was that people don't have to train their own lung segmentation for each new dataset. The R231 works quite well on COVID-19 cases. For a detailed description how and on which data the R231 model trained consult the [publication ](https://arxiv.org/abs/2001.11767). 

> What do you think is the best solution for me?
I think the best solution for you is to use the R231 or R231CovidWeb model. They should both work well. Use the R231CovidWeb when you have images that were converted back from e.g. jpg to HU or which were annotated or cropped.

> Another solution would be to be able to add the data I will produce and fine-tune/retrain your model as more data get collected, would that be desirable/doable, in my case ?
The data I used is not cleared for sharing as of yet. Once the data is released you could do that. However, you have to find a set of scans where the current model fails (I would say 10 or more). Once you have that, it would be very useful to retrain.
