### ISSUE TITLE
Meaning of values returned by mask.apply(input_image) using U-net(R231) model?

### ISSUE THREAD

**Issue by AlphonsG** [JoHof/lungmask#61]
Thank you for this repo. I was just curious about the meaning of the values in the array returned by the segmentation function mask.apply(input_image). I know 0 is the background, 1 and 2 are the lungs, but are other values possible and what do they mean? For example, I think the model detects air pockets?

**Comment by JoHof** [comment]
Hi Alphons, 1 is the right lung and 2 the left lung. There are no other values. Air pockets and also effusions are included in the segmentation.

**Comment by AlphonsG** [comment]
Alright, thanks very much for the response!
