### ISSUE TITLE
Add option for verbosity

### ISSUE THREAD

**Issue by andreasala98** [JoHof/lungmask#66]
Hey everyone,
thanks for the great package that you've developed.

I need to include mask making inside a wider pipeline. Could it be possible if you added an argument `verbose` that allows the user to avoid printing the `tqdm` progress bar and all other checkpoints/warnings?

If needed, I could give some help myself.

Thanks and take care
Andrea

**Comment by JoHof** [comment]
There is now an option to disable the tqdm
