### ISSUE TITLE
Publish package

### ISSUE THREAD

**Issue by andreasala98** [JoHof/lungmask#67]
Hi,
could you please publish the package on Pypi?

**Comment by JoHof** [comment]
Hi Simon,

thanks for the Information! Congratulations on your success!

best,
Johannes

Am Di., 27. Sept. 2022 um 14:04 Uhr schrieb Simon Jégou <
***@***.***>:

**Comment by JoHof** [comment]
Hi Simon,

Could you please add me as a maintainer to the lungmask project on pypi? My
username is 'jhofmanninger' (https://pypi.org/user/jhofmanninger/)

best,
Johannes

Am Di., 27. Sept. 2022 um 19:18 Uhr schrieb Johannes H <
***@***.***>:

**Comment by SimJeg** [comment]
done ! I also added you as a contributor on the github fork
