### ISSUE TITLE
`LMInferer` should be instantiated with a model (or model path) as a parameter

### ISSUE THREAD

**Issue by gacou54** [JoHof/lungmask#82]
Hi!

Users must download the model when instantiating the `LMInferer` (see below). In some environments (e.g. some Slurm clusters), internet access is restricted, which makes `lungmask` raise an error.

```python
class LMInferer:
    def __init__(...):
        ...
        # here (mask.py:115), raise an error in restricted network environments
        self.model = get_model(self.modelname)
```

I suggest that the `LMInferer` class should have a `model` parameter instead of a `modelname`, or at least a `modelpath` parameter.

Personal opinion: In my mind, `LMInferer` should not have the responsibility to load or download the `model`. I prefer the option where the  `model` is given as a parameter

Thank you for this project :)

**Comment by JoHof** [comment]
Hi, 

thanks for your feedback, that's actually a really good point. I think though it should be the responsibility of `LMInferer` to load the model. Why would you prefer to pass the model directly if may ask? I needs extra code to load the model and pass it to the constructor. I would add just a parameter for modelpath as alternative to the modelname. What do you think?

**Comment by gacou54** [comment]
`Why would you prefer to pass the model directly if may ask?` In my mind, the `LMInferer` role should be to "infer/apply" the model (from a software architecture/engineering point of view). But its only details and it would indeed require you to write more code. 

`I would add just a parameter for modelpath as an alternative to the modelname. What do you think?` It is indeed the simplest fix and I am totally good with it.

Thank you again!
