### ISSUE TITLE
how to quit lungmask environment after using

### ISSUE THREAD

**Issue by Sere1nz** [JoHof/lungmask#85]
![image](https://github.com/JoHof/lungmask/assets/32921181/e4d4bd09-b0a0-495b-8bf3-eb239fbb9683)
Hi, how can I quit lungmask environment after using it. Normally there wont be "lungmask" sign in front of logging. It seems if i run lungmask for segmentation first, then my rest of operaions after segmentation will always be ran in the lungmask environement. I test that in lungmask environment the other/rest of my script operations(like sitkwrite images, merging, centerline generation which dont need to be run in lungmask) go slower, so I want to quit/end lungmask environment after using it for segmentation. How can I do it? Thank you!

**Comment by JoHof** [comment]
there is not such thing as a lungmask environment. what you see is the basic logger configuration set by lungmask. This should be fixed now (version 0.2.16)
