### ISSUE TITLE
Problems about blog post ( map images back to HU)

### ISSUE THREAD

**Issue by yandamengdanai** [JoHof/lungmask#9]
Hi, thank you for your work, and I follow the step by step in blog post and try to map images back to HU, but it seems something wrong with normalize_function, the value inside the function will be air = 1, ratio = 900, air_HU = -1000, with air = 1 and fat = 2 as the input , is that correct? But with this setting, the images can't map back to the HU i think, please help me with that. 

Best

**Comment by JoHof** [comment]
Hi,
I didn't write this blog post. However, air and fat have to be the values that air and fat have in the jpg image. You have to measure them manually
