### ISSUE TITLE
SimpleITK

### ISSUE THREAD

**Issue by rbumm** [JoHof/lungmask#92]
Hi Johannes,
lungmask is heavily used by 3D Slicer users, which is great. 
Unfortunately, it uses

Name: SimpleITK
Version: 2.2.0rc2.dev368
Summary: SimpleITK is a simplified interface to the Insight Toolkit (ITK) for image registration and segmentation
Home-page: http://simpleitk.org/
Author: Insight Software Consortium
Author-email: insight-users@itk.org
License: Apache
Location: c:\users\rudolf\appdata\local\slicer.org\slicer 5.4.0\lib\python\lib\site-packages
Requires: 
Required-by: lungmask
 
TotalSegmentator, which is also in 3D Slicer,  in turn, uses

Name: SimpleITK
Version: 2.3.0
Summary: SimpleITK is a simplified interface to the Insight Toolkit (ITK) for image registration and segmentation
Home-page: http://simpleitk.org/
Author: Insight Software Consortium
Author-email: insight-users@itk.org
License: Apache
Location: c:\users\rudolf\appdata\local\slicer.org\slicer 5.4.0_2\lib\python\lib\site-packages
Requires: 
Required-by: acvl-utils, lungmask, nnunetv2, TotalSegmentator

Any chance to update the SimpleITK version of lungmask to 2.3.0 ? 
Currently it fails under this version. 

Best
Rudolf

**Comment by JoHof** [comment]
Hi Rudolf,

The setup.py doesn't fix the version of sitk so there shouldn't be a conflict in pip. The requirements.txt just reflects the dev environment and can be ignored. How did you run into issues?

**Comment by rbumm** [comment]
![image](https://github.com/JoHof/lungmask/assets/18140094/290b2b3b-8a90-4b41-a27e-37bd371ca43a)

**Comment by JoHof** [comment]
hm, would love to help but I don't understand the issue. lungmask does not require SimpleITK 2.2.0 and I don't find any issues with it with 2.3.0 either.  If you install lungmask from pip it should use SimpleITK 2.3.0. 

1) Is the build system you are using maybe considering the requirements.txt file? Can you check by creating a branch without the requirements.txt file? I don't know how python packages are used inside Slicer.

2) Are you sure this is connected to lungmask at all? Could there be an issue with Totalsegmentator requirements eventually? E.g. requiring vtk though the fury library?

**Comment by JoHof** [comment]
Hi Rudi,

has there been any development on this?

**Comment by rbumm** [comment]
How did you install TotalSegmentator v2?
Simple pip install must not be used (there are incorrectly hardcoded dependencies) but the SlicerTotalSegmentator extension's selective dependency installation technique works well: it does not replace SimpleITK.

Andras

________________________________
