### ISSUE TITLE
Can I extract the exterior polygons of the thorax and the polygons of lungs?

### ISSUE THREAD

**Issue by liubenyuan** [JoHof/lungmask#94]
Hi, I need to do triangle mesh processing on lungs, can I extract the exterior (shape) of the thorax as well as the polygons of the lungs using `lungmask`?

**Comment by JoHof** [comment]
No, lungmask will give you a segmentation on the voxel level, it will not produce any surface. If you want a mesh you need to do something like this: 
[](https://stackoverflow.com/questions/69524209/how-to-generate-3d-mesh-from-a-numpy-binary-mask)
