### ISSUE TITLE
Failed to compute results: module ‘torch.backends’ has no attribute ‘mps’ ERROR

### ISSUE THREAD

**Issue by JohanDiazTovar** [JoHof/lungmask#97]
Hello everyone, I recently updated 3D slicer to the version 5.60 and when I’m trying to use the Lung CT Segmenter extension (which it was working before) I’m getting this error:

Failed to compute results: module ‘torch.backends’ has no attribute ‘mps’

I already checked the updates for PyTorch and the lungmask library, I even installed the version that was working before (5.40) but even doing that it is not working and giving me the same error, what do you thinkg I can do…

I’m using 3D slicer in a Mac

**Comment by JoHof** [comment]
Hi Johan,

sorry, I missed your post. Seems like an old torch version (<1.12). I updated the package to check for this and it should not fail with this error enymore
