### ISSUE TITLE
Segmentation names

### ISSUE THREAD

**Issue by Renal-Of-Loon** [JoHof/lungmask#98]
Hello there,

I'm fairly certain this must be available _somewhere_, but I can't seem to find a way to identify the name of each masks after using the example 

```py
inferer = LMInferer(modelname="LTRCLobes")
result = inferer.apply(input_image)
```
`result` seems to be the ndarray, and I'm not sure how to obtain what ROI name is associated for each mask value. Is this hardcoded somewhere, or available within the inferer class?

**Comment by JoHof** [comment]
Hi,
you are right this is missing. I added the information to the readme with PR #99
